#!/usr/bin/env python3

import regex as re
from datetime import datetime
from typing import List, Callable
from pathlib import Path

import pandas as pd
import numpy as np
import click
import matplotlib.pyplot as plt
import xlrd
import requests
import urllib.request
from bs4 import BeautifulSoup


def _get_xls_url() -> str:
    url = "https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide"
    page = requests.get(url)
    soup = BeautifulSoup(page.text, "html.parser")
    xls_link_box = soup.find("a", href=re.compile(r".+\.xls"))
    return xls_link_box["href"]


def _download_file_cached(
    get_url: Callable[[], str], path: Path, cache_expire: int = 300
):
    # TODO: Test file before saving (in case file is malformed)
    if (
        not path.exists()
        or path.lstat().st_mtime < datetime.now().timestamp() - cache_expire
    ):
        print("Downloading file...")
        _download_file(get_url(), path)
    else:
        print("Used cache")
    return path


def _download_file(url: str, path: Path) -> Path:
    r = requests.get(url)
    path.open("wb").write(r.content)
    return path


@click.group()
def main():
    """Tools to analyze cases and deaths from COVID-19"""
    pass


def _load_df() -> pd.DataFrame:
    path = Path("data.xls")
    _download_file_cached(_get_xls_url, path)
    return pd.read_excel(path, index_col="DateRep", parse_dates=True).sort_index()


@main.command()
@click.argument("regions", nargs=-1, required=True)
@click.option("--cum", is_flag=True, help="Plot cumulative cases/deaths")
@click.option("--deaths", is_flag=True, help="Plot deaths")
@click.option("--log", is_flag=True, help="Use a log scale on the y-axis")
@click.option("--bar", is_flag=True, help="Use a bar plot instead")
@click.option("--until")
def plot(
    regions: List[str], cum: bool, deaths: bool, log: bool, bar: bool, until=None,
):
    """Plot cases (by default) or deaths for different regions"""

    cases_or_deaths = "Cases" if not deaths else "Deaths"
    regions = _filter_regions([r.lower() for r in regions])

    df = _load_df()

    df = df[df["Countries and territories"].str.lower().isin(regions)]
    df = df.pivot(columns="Countries and territories", values=cases_or_deaths)

    # Remove rows before first case
    df = df.truncate(before=df.sum(axis=1).ge(1).idxmax())

    if cum:
        df = df.cumsum()

    if until:
        df = df.loc[: pd.Timestamp(until)]

    plotf = df.plot if not bar else df.plot.bar
    plotf(logy=log)

    new_or_cum = "Cumulative" if cum else "New"
    plt.ylabel(f"{new_or_cum} {cases_or_deaths.lower()}")
    plt.title(
        f"COVID-19 {new_or_cum} {cases_or_deaths.lower()} as of {max(df.index).date()}"
    )
    plt.ylim(1)
    plt.legend()
    _draw_watermark(plt.gcf())
    plt.show()

    # Saving figure
    plt.savefig("output.png")


def _filter_regions(regions: List[str]) -> List[str]:
    df = _load_df()
    all_regions = set(df["Countries and territories"].str.lower())
    # print(sorted(all_regions))
    for region in regions:
        if region not in all_regions:
            print(f"Error: Region '{region}' does not exist in the dataset")
            regions.remove(region)
    return regions


@main.command()
@click.argument("regions", nargs=-1, required=True)
def fatality(regions: List[str]):
    regions = _filter_regions(regions)

    df = _load_df()
    df = df[df["Countries and territories"].str.lower().isin(regions)]
    df_c = df.pivot(columns="Countries and territories", values="Cases")
    df_d = df.pivot(columns="Countries and territories", values="Deaths")
    df = df_d.cumsum() / df_c.cumsum()

    # Remove rows before first case
    df = df.truncate(before=df.sum(axis=1).ge(0).idxmax())

    (df * 100).plot()

    plt.title("COVID-19 fatality rate (total deaths / total cases)")
    plt.text(
        0.5,
        0.98,
        "Note: heavily influenced by testing capacity of each country",
        horizontalalignment="center",
        verticalalignment="center",
        transform=plt.gca().transAxes,
        color="gray",
    )
    plt.ylabel(f"Rate (%)")
    plt.xlabel("")
    plt.ylim(0)
    _draw_watermark(plt.gcf())
    plt.show()


def _draw_watermark(fig):
    fig.text(0.01, 0.01, "Data from www.ecdc.europa.eu", ha="left", va="bottom")
    fig.text(0.99, 0.05, "Built by @ErikBjare, @karvla, et al", ha="right", va="bottom")
    fig.text(
        0.99, 0.03, "Generated by covid19count", ha="right", va="bottom",
    )
    fig.text(
        0.99,
        0.01,
        "https://github.com/karvla/covid19count",
        color="gray",
        ha="right",
        va="bottom",
    )


if __name__ == "__main__":
    main()
